//! External-oracle validation for the Rust logicle port. The CSV is generated by
//! scripts/golden/gen_logicle_golden.py from flowutils (FlowKit's logicle C
//! extension / Moore & Parks 2012). Embedded with include_str! so it runs in CI
//! with no file-path or serde dependency.

use joeee_cytometry_wasm::logicle::Logicle;

const GOLDEN: &str = include_str!("logicle_golden.csv");

#[test]
fn forward_scale_matches_flowutils() {
    let mut rows = 0usize;
    let mut max_err = 0.0f64;

    for line in GOLDEN.lines().skip(1) {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let f: Vec<f64> = line.split(',').map(|s| s.trim().parse().unwrap()).collect();
        let (t, w, m, a, x, expected) = (f[0], f[1], f[2], f[3], f[4], f[5]);
        let lg = Logicle::new(t, w, m, a);
        let got = lg.scale(x);
        max_err = max_err.max((got - expected).abs());
        rows += 1;
    }

    assert!(rows > 0, "no golden rows parsed");
    assert!(
        max_err < 1e-9,
        "Rust logicle deviates from flowutils oracle by {max_err:e} over {rows} rows",
    );
}
